buf.yaml

So we can publish this to the buf repository

Updating name of buf module

---

.github/workflows/buf.yml

This action will push protos to Buf Schema Repository, which is used by the SDKs (python only for now)

Push protos to Buf Schema Repository

---

artifact/fs_store.go

Makes AtomicStore more easily accessible to allow for safer cloud caching of robot configs in RSDK-305.
Since this is an extremely trivial change, `make build lint` should be sufficient testing.

RSDK-319 - refactor to make AtomicStore more accessible

---

.github/workflows/buf.yml

Adding rust-sdk in the buf dispatch workflow

Add rust-sdk in buf dispatch

---

Makefile
rpc/examples/echo/Makefile
rpc/examples/echo/frontend/webpack.config.js
rpc/examples/fileupload/Makefile
rpc/examples/fileupload/frontend/webpack.config.js

So while all my tests ran locally... I actually forgot to run them in the current version of canon, so these are the fixes needed for that.
On the upside, this should be a good test of the new workflow handling.

Fix NPM builds

---

io.go

related to [RSDK-503] to add closer than we can compare with
[RSDK-503]: https://viam.atlassian.net/browse/RSDK-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

add ContextCloser

---

.github/workflows/license_finder.yml
doc/dependency_decisions.yml

JIRA: https://viam.atlassian.net/browse/RSDK-652
Covered by a subset of existing license policy in https://github.com/viamrobotics/rdk

RSDK-652: Audit OSS

---

rpc/dial_options.go
rpc/dialer.go
rpc/dialer_test.go

JIRA: https://viam.atlassian.net/browse/RSDK-578
Required for https://github.com/viamrobotics/rdk/pull/1501

RSDK-578 Add client interceptors

---

.github/workflows/license_finder.yml
.github/workflows/proto-checks.yml
.github/workflows/publish.yml
.github/workflows/test.yml
proto/rpc/examples/fileupload/v1/fileupload.pb.go
proto/rpc/webrtc/v1/grpc.pb.go
proto/rpc/webrtc/v1/signaling.pb.go

Basic lint changes against the new canon with go 1.19.

Lint for go 1.19

---

rpc/server_auth.go

if we updated rdk/app as is, we would probably get some robots locked out

rpc: do not enforce subject claim for now

---

rpc/dial_test.go
rpc/examples/echo/server/server.go
rpc/server.go
rpc/wrtc_call_queue.go
rpc/wrtc_call_queue_memory.go
rpc/wrtc_call_queue_memory_test.go
rpc/wrtc_call_queue_mongodb.go
rpc/wrtc_client_test.go
rpc/wrtc_server_channel_test.go
rpc/wrtc_signaling_answerer.go
rpc/wrtc_signaling_server.go
rpc/wrtc_signaling_test.go

rpc: fix various signaling concurrency and performance issues

---

jwks/jwks.go
jwks/jwks_test.go
rpc/oauth/web_oauth.go
rpc/oauth/web_oauth_test.go

- Support access to keyset from KeyProvider interface
- Web Oauth supports multiple valid aud claims. (minor breaking changes in app)

minor updates to web auth

---

pexec/managed_process.go

8) - any feedback on what character to use would be appreciated

pexec: improve logs

---

.github/workflows/pr-labeler.yml

To help search for PRs by non org members.

Label PRs with viam-org for org members

---

Makefile
rpc/examples/echo/frontend/package-lock.json
rpc/js/.prettierignore
rpc/js/package-lock.json
rpc/js/package.json
rpc/js/src/BaseChannel.d.ts
rpc/js/src/BaseChannel.ts
rpc/js/src/BaseStream.d.ts
rpc/js/src/BaseStream.ts
rpc/js/src/ClientChannel.d.ts
rpc/js/src/ClientChannel.ts
rpc/js/src/ClientStream.d.ts
rpc/js/src/ClientStream.ts
rpc/js/src/dial.d.ts
rpc/js/src/dial.ts
rpc/js/src/errors.d.ts
rpc/js/src/errors.ts
rpc/js/src/index.ts
rpc/js/src/peer.d.ts
rpc/js/src/peer.ts
rpc/js/webpack.config.js

Format JS/TS code via prettier

Format JS/TS

---

rpc/wrtc_base_stream.go
rpc/wrtc_server_stream.go

A server stream object (and its underlying incoming message channel) is shared by two goroutines. We will name those goroutines the "receiving" goroutine and the "processing" goroutine. Typically, the processing goroutine will be responsible for closing resources when the stream is finished. A stream can finish for (broadly) two reasons:
- A message with the eos (end-of-stream) flag is processed.
- Processing a message results in an error.
Notably in the case where processing a message encounters an error (e.g: session expiration), the code to close the stream can happen concurrently with a new message being received. The stream mutex must be held to reliably wait for any in-flight requests to be processed or canceled.

RSDK-3297: Server streams must hold the stream mutex when closing receivers.

---

.github/workflows/test.yml
Makefile
README.md
rpc/examples/echo/.gitignore
rpc/examples/echo/Makefile
rpc/examples/echo/frontend/src/index.ts
rpc/examples/echo/package-lock.json
rpc/examples/echo/package.json
rpc/examples/echo/playwright.config.ts
rpc/examples/echo/server/templates/index.html
rpc/examples/echo/tests/echo.spec.ts

Run echo example in CI so we have some JS test coverage. 
* Note that the CI run below uses the workflow definition on `main` and doesn't include the new JS test. I ran the JS tests in a separate action: https://github.com/viamrobotics/goutils/actions/runs/7051309320
Also add a minimal UI to the example instead of just logging to the console:

RSDK-851 rpc js tests

---

rpc/examples/echo/frontend/package-lock.json
rpc/js/package-lock.json
rpc/js/package.json

Publish the fix from https://github.com/viamrobotics/goutils/pull/231

Bump RPC version

---

go.mod
rpc/dial.go

Add cause to parallel dial cancellation.

RSDK-6151: Add cause to parallel dial cancellation

---

.github/workflows/test.yml

Add back TEST_SUBPROC_USER in the 'run as user'
:heavy_check_mark: Passing [here](https://github.com/viamrobotics/goutils/actions/runs/7905086408/job/21576879796#step:15:76)

APP-3946 run_as_user test

---

web/auth0.go

Depending on auth provider, we need to populate post logout redirect URL with different query params.

[APP-3046] Post logout redirect URL update.

---

rpc/wrtc_signaling_server.go

RSDK-5690
Better synchronize active goroutines in `wrtc_signaling_server.go`. Very similar to change in https://github.com/viamrobotics/goutils/pull/251 and https://github.com/viamrobotics/goutils/pull/262.
- Renames `activeBackgroundWorkers` to `callWorkers`
- Adds a `callMu` `RWMutex` to be `RLock`ed when adding a call worker and `Lock`ed when waiting on call workers
The linked ticket describes a data race where `activeBackgroundWorkers.Add(1)` was racing with `activeBackgroundWorkers.Wait()`. This was happening because the `Add` was in a separate goroutine from the `Wait` due to the asynchronous nature of our call process, and there was no synchronization of `Add`s and `Wait`s.

RSDK-5690 Better synchronize call workers and Close

---

etc/setup_priv_key.sh
jwks/jwks.go
rpc/auth.go
rpc/auth_test.go
rpc/dial_test.go
rpc/examples/echo/server/cmd/main.go
rpc/examples/fileupload/server/cmd/main.go
rpc/server.go
rpc/server_auth.go
rpc/server_auth_test.go
rpc/server_options.go
rpc/server_test.go

- And support multiple keys for verification and select one for signing

RSDK-6883 rpc: Replace RS256 with EdDSA as default signing algo

---

web/auth0.go

[internal Viam Slack message](https://viaminc.slack.com/archives/C03G6S6GU8J/p1711387471215149) reporting this issue. Thanks for looking out, @mcous!

remove token debug line

---

rpc/dial_test.go
rpc/server_auth.go
rpc/server_auth_jwks_test.go
rpc/server_auth_test.go

[APP-4297](https://viam.atlassian.net/browse/APP-4297)
[APP-4297]: https://viam.atlassian.net/browse/APP-4297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

APP-4297: removed noisy logs, added additional logs

---

string_test.go

RSDK-7975 Fix TestStringSet

---

rpc/js/src/dial.ts

[RSDK-7283](https://viam.atlassian.net/browse/RSDK-7283)
Adds debug-level logs for:
- Gathering of local ICE candidates
- Reception of remote ICE candidates
- Statistics of caller updates for this connection establishment
- Number of updates
- Average duration of update
- Max duration of update
[RSDK-7283]: https://viam.atlassian.net/browse/RSDK-7283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-7283 Add logs for timing of ICE events to TS dial code

---

rpc/wrtc_server_stream.go

I noticed this failure in https://github.com/viamrobotics/goutils/actions/runs/9860875871/job/27228052504?pr=305. There's a chance that headers are not written by the time SendMsg is called which results in a RLock being called twice.

RSDK-8139 - rpc: only take RLock after writeHeaders in webrtcServerStream.SendMsg

---

README.md
rpc/doc.go

RSDK-8097 - update readme

---

.github/workflows/publish.yml

- download protoc-gen-grpc-web
- add workflow_dispatch (which just runs `make` step, not publish) so we can test this without merging
Job is failing on main

fix publish.yml post upgrade

---

rpc/dial_options.go

RSDK-8658 - Add clarifying comment around WithForceDirectGRPC

---

logger.go
rpc/server.go
rpc/server_interceptors.go
rpc/wrtc_client_channel.go

This reverts commit 52a853a95a0e90b24c9bf18a87fece011c6c25e4.

Revert "[RSDK-9149] Use RDK Logger Across Interceptors (#400)"

---

rpc/wrtc_call_queue_memory.go
rpc/wrtc_signaling_answerer.go
rpc/wrtc_signaling_server.go
stoppable_workers.go

_**WIP**_
_Not done yet. Do not approve/merge._

[RSDK-8666] Use StoppableWorkers in WebRTC Signaling Process

---

go.mod
go.sum
rpc/dial.go
rpc/server.go

RSDK-10323 Use updated zeroconf that responds to plain mDNS questions

---

rpc/server.go

might not be strictly necessary for what the ask is (disabling TLS), but this was already inflight, so figured I should finish this.
tested pings from another pi
tested Go SDK mDNS connections from same computer
tested pings from same computer

RSDK-10402 - Fix pings to machine-name.local 

---

net.go

This is needed for [this change](https://github.com/viamrobotics/app/pull/8532) - more details on that PR.

DATA-4118 - Add ReserveRandomPort

---

rpc/server_test.go

Bug described in https://viam.atlassian.net/browse/RSDK-10971

RSDK-10971: Fix test asserting on async behavior.

---

rpc/wrtc_server_channel.go

so that stream limit hit logs will be deduped (the channel id shouldn't be relevant for that log)

Move server stream logger init

---

etc/.golangci.yaml

Almost identical to https://github.com/viamrobotics/rdk/pull/5105 but fewer changes were needed.

Get rid of all linter warnings
