viamrobotics/goutils

.github/workflows/buf.yml

Per our conversation @Otterverse, this PR updates the workflow runner to use the canon image

Change workflow runner image for buf

---

.github/workflows/buf.yml

Repo dispatch syntax is not what I expected therefore dispatch action are only applied to python-sdk and not rust-sdk
See [here](https://github.com/marketplace/actions/repository-dispatch) for the proper syntax

Fixing workflow

---

pexec/managed_process.go
pexec/managed_process_test.go
pexec/process.go

There are 3 PRs necessary to reserve the port in the slam process:
https://github.com/viamrobotics/slam/pull/29: orbslam reserves and logs the port
https://github.com/viamrobotics/goutils/pull/50 (this PR): add support for extracting log lines from managed processes
https://github.com/viamrobotics/rdk/pull/1269: slam service reads port from orbslam logs
https://github.com/viamrobotics/rdk/pull/1269 must be merged after https://github.com/viamrobotics/slam/pull/29 and https://github.com/viamrobotics/goutils/pull/50.

[DATA-298] Support getting log lines from managed processes

---

rpc/wrtc_client_channel.go

wrtc client is currently really noisy and we want the client logs to be set to debug if no error is found

[RSDK-731] Handle wrtc noisy client

---

perf/exporters.go
perf/metrics.go

In dev mode we were printing the metrics recorded ever 5 seconds. This was a lot and not useful. Getting rid of it. Trace logging stays since that is our only local HTTP request(ish) logging in the app locally.

Remove development metrics logger

---

web/api.go
web/error.go
web/panic_capture.go
web/panic_capture_test.go
web/templates.go

I found cases today where we are panicing in the app but the logs go unnoticed because the logs are split between stackdriver lines.
This includes a panic capure to the template handler and api handler.
It includes basic error logging for cases where we return a 5xx to the user.

Support better error logging in the HTTP service.

---

protoutils/protoutils.go
protoutils/protoutils_test.go

There are certain `protoutils` functions that lived in `rdk` that we want to use in `app` as well. This PR introduces those functions to `goutils` so they can be shared between applications.

Move select protoutils functions from rdk to goutils

---

web/api.go
web/api_test.go
web/error.go
web/protojson/marshaler.go
web/protojson/marshaler_test.go
web/protojson/options.go
web/templates.go
web/templates_test.go
web/testdata/templates/nonProtoJson.html
web/testdata/templates/protoJson.html

This changes includes a custom json marshaler that wraps the normal json.Marshal and protojson.Marshal. It will determine if the passed in data is a proto.Message or slice of proto.Messages and if so use the protojson.Marshal instead of the json.Marshal. Otherwise it will fallback to json.Marshal()
It also includes a new template function called `protoJson` which uses the custom marshaler. We can use this now in our templates when we pass data to the window that should be serialized with the protjson.

Support for protojson encoding in API Middleware and Template Middleware

---

.github/workflows/publish.yml

CI publishing of the RPC NPM library isn't working. I'm unsure of what the problem is [but it seems related to the golang linter](https://github.com/viamrobotics/goutils/actions/runs/3207545693/jobs/5242534039). For now I'm disabling the step so that others can produce clean builds with nice green checkmarks.

Turn off CI npm publishing until bug is fixed

---

rpc/server.go

Ensure we use proto field names instead of json names.

Match our grpc-gateway json settings to our legacy api.

---

rpc/auth.go
rpc/context.go
rpc/server_auth.go
rpc/server_auth_test.go

To support other use-cases where the JWT claims may contain other metadata about the entity or require validation outside the standard JWT claims we expose a way to get all claims in the auth handler.

APP-823 custom claims in rpc AuthHandler

---

Makefile
README.md

Allows example make recipes to be run from the root of this repository.
For example, the echo server can be run via:
```
make example-echo/run-server
```

Add example make recipes to top-level makefile

---

testutils/wait.go

Some time-sensitive tests need to tweak the sleep value. The default 50ms value is too high.

Add WaitForAssertionWithSleep testing util

---

jwks/jwksutils/utils.go
rpc/auth.go
rpc/auth_test.go
rpc/oauth/testutils/utils.go
rpc/oauth/web_oauth.go
rpc/oauth/web_oauth_test.go
rpc/server.go
rpc/server_auth.go
rpc/server_auth_test.go
rpc/server_test.go

Distinguish between `aud` (audience) and `sub` (subject) claims. Audience should generally be used to indicate what the authentication token is used against. While the `sub` indicates who the owner of the token is. Eg. user entity.
By default simple auth handlers and Authenticate request only accept an entity which is used as both the audience and the subject.
However AuthenticateTo now uses the entity of the original Authenticate request as the subject and the audience as the entity its Authenticating To.
Add SHA-1 thumbprint as the `kid` to all JWTs created by the RPC framework.
Background on JWT claim usage: See: https://www.rfc-editor.org/rfc/rfc7519#section-4.1
[4.1.2](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.2).  "sub" (Subject) Claim
The "sub" (subject) claim identifies …

APP-1068 - Add subject and kid support in JWT

---

pexec/managed_process.go
rpc/dial.go
rpc/dial_options.go
rpc/dial_test.go

Two changes needed to support modular resources. (Note, this PR should probably not be merged until the big mod resources PR in RDK is ready to merge, in case other changes are needed here.)
1. This adds support to make a direct connection attempt the primary for unix sockets (and an option to do so for other possible use cases in the future.)
2. It adds Segpgid to ManagedProcess configuration. This prevents background processes spawned from getting foreground signals. For example, without this, hitting CTRL+C on a running viam-server also directly sent that SIGINT to the module. Now it will only be seen by the parent viam-server process, which can then handle stopping the background process/module in a clean way.
3. It switches the pexec final SIGKILL to signal the entire progress group …

Changes to support Modular Resources (Includes RSDK-472 )

---

rpc/dial.go
rpc/dial_options.go
rpc/dial_test.go
rpc/dialer.go
rpc/wrtc_client.go

- Support external auth with a static credential.
- Smart enough to figure out that when an external auth / signaler is used vs a local signaler when on mdns.

Dial support for external auth with static credentials

---

rpc/dialer.go
rpc/dialer_test.go

Comments inline to explain, but tl;dr is lock contention. The cachedDialer can be put into the context, and thus gets reused by various dial functions. Dialing with Auth, for example, reuses the dialer from different layers, resulting in the possibility of nested refCountedConnWrapper and thus, deadlock on Close.
Note: RDK needs to be bumped with this update after this merges.

RSDK-1660 - Fix deadlock in cachedDialer

---

rpc/examples/echo/Makefile
rpc/examples/echo/frontend/src/index.ts
rpc/examples/echo/server/cmd/main.go
rpc/examples/echo/server/templates/index.html
rpc/js/src/dial.ts

JS RPC library updated to allow authToAddress and authToEntity with accessToken set in the dial options. This will force the accessToken to be used for the AuthenticateTo request but use the returned access token in signaling or direct rpc calls.
If authTo options are omitted while an accessToken is present all Authenticate/AuthenticateTo calls will be bypassed.

APP-1153 - Support using access token with external auth in JS

---

web/auth0.go

Currently it is set at 1 minute which does not give enough time to some users. Users may get side tracked during the login flow or take a while to sign up with google + two factor login.
This increases the time to 10m.
However we should also gracefully handle the error in a further fix like redirecting to the /login handler again.

fix: Allow 10m for a user to login through google/auth0

---

rpc/dial.go
rpc/dial_test.go
rpc/server.go

This PR replace any  '.' in robot's fqdn or local_fqdn with '-' ('.' are not skipped properly when sending the advertisement packets therefore violating mDNS RFC) . The robot's mDNS records can now be properly parsed by other mDNS discovery tools, the robot can also question record from other implementation (mini-rdk) properly
The former service advertisement is kept for backward compatibility.

[RSDK-1676] Replace . with - when advertising robot over mdns.

---

pexec/managed_process.go
pexec/managed_process_test.go
pexec/managed_process_unix.go
pexec/managed_process_windows.go
pexec/process.go
pexec/process_manager_test.go
pexec/process_test.go
pexec/verify_main_test.go
testutils/file.go

I'll add a runner later to support this but need to deal with other issues first. Essentially, killing in Windows is very hard without signals and a custom made binary.

pexec: better support windows

---

web/auth0.go

So somehow i didn't actually update the max age of the cookie when i submitted https://github.com/viamrobotics/goutils/pull/126/files i just refactored it :(

fix: increase redirect cookie max age to 10m

---

README.md

Changing `example` to `examples` in both links fixed the broken links.

Fix broken links to 'echo' and 'fileupload'

---

web/sessions.go

- Allows being able to link from external web page to Viam.com and have auth work. Still protects against most CSRF assuming GET requests has no affect on system.

Allow for Lax Session Cookie.

---

mongo/change_stream.go
mongo/change_stream_test.go
perf/metrics.go
perf/mongodb.go
rpc/dial_test.go
rpc/wrtc_call_queue.go
rpc/wrtc_call_queue_memory_test.go
rpc/wrtc_call_queue_mongodb.go
rpc/wrtc_call_queue_mongodb_test.go
rpc/wrtc_call_queue_test.go
rpc/wrtc_client_test.go
rpc/wrtc_signaling_test.go

This improvement has been a long time coming. This makes using the MongoDB queue much more efficient while also adding in some nice soft-limits.

RSDK-236 RSDK-248 - rpc: use single changestream per mongoDBWebRTCCallQueue

---

.github/workflows/publish.yml

This will make publishes consistent with our other JS repos. By default this gracefully aborts if there is no JS version bump (as opposed to https://github.com/viamrobotics/goutils/commit/90cacc93efe0c62ceae13fd718960d1a8c043595)

Use npm publish action

---

.github/workflows/publish.yml

Ran into an issue similar [to this one](https://github.com/JS-DevTools/npm-publish/issues/78), and seems like the advice is to upgrade to the v2 action. 
I also updated config to point to the package.json file instead of just the sub-directory (seems like either should work based on the docs but [the advice to specify the `package.json` file is a bit more explicit](https://github.com/JS-DevTools/npm-publish#usage-1))

Use npm publish action v2

---

pexec/managed_process.go
pexec/managed_process_test.go
pexec/process.go

Reverts viamrobotics/goutils#155
Reverting as this change causes issues when reflection is used to marshal `OnUnexpectedExit` within `ProcessConfig`.

Revert "RSDK-2425 Add OnUnexpectedExit to managed processes"

---

pexec/managed_process.go
pexec/managed_process_test.go
pexec/process.go

[RSDK-2425](https://viam.atlassian.net/browse/RSDK-2425)
Same as #155, but with `jsonschema:"-"` on `OnUnexpectedExit` to avoid panics when trying to reflect the schema of `ProcessConfig` (functions cannot be encoded to JSON).
[RSDK-2425]: https://viam.atlassian.net/browse/RSDK-2425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
cc @sbal13

RSDK-2425 Add OnUnexpectedExit to managed processes (redo)

---

rpc/server.go

This covers a case where the loopback adapter doesn't support multicast, such as in some docker containers (usually cross-architecture emulation.)

RSDK-2545 Allow fail-through for mDNS

---

rpc/server.go
rpc/wrtc_base_channel.go
rpc/wrtc_base_stream.go
rpc/wrtc_client_channel_test.go
rpc/wrtc_client_stream.go
rpc/wrtc_server_channel.go
rpc/wrtc_server_stream.go
rpc/wrtc_signaling_answerer.go

This also makes sure we serialize writes coming in more clearly

rpc: mitigate some client close error races

---

rpc/server.go
rpc/server_options.go

We want to add a health check to grpc for deployment. To do so, we need to bypass the authentication methods required for the rest of the app. 
This is part of 3 prs that will need to be merged, but this is the first:
https://github.com/viamrobotics/api/pull/258

APP-1218: Adding unauth option for health check

---

protoutils/protoutils.go
protoutils/protoutils_test.go

[RSDK-2796](https://viam.atlassian.net/browse/RSDK-2796)
Allows map keys to be non-strings that implement [`fmt.Stringer`](https://pkg.go.dev/fmt#Stringer). Adds tests that those maps can be marshaled and maps with non-string types that do not implement `Stringer` still cannot be.
[RSDK-2796]: https://viam.atlassian.net/browse/RSDK-2796?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RSDK-2796 Allow map keys to be non-strings that implement String

---

rpc/wrtc_base_channel.go
rpc/wrtc_peer.go

[RSDK-3026](https://viam.atlassian.net/browse/RSDK-3026)
Ignores and debug-logs `User Initiated Abort: Close called` errors. Also ignores `dtls.ConnIsClosed` errors that occur when the peer connection has already been closed by the other side.
Certain browsers close RTC peer connections through an ["upper-layer request"](https://www.tech-invite.com/y45/tinv-ietf-rfc-4960-3.html#e-3-3-10-12) that sends an abort chunk error that, [as of relatively recently](https://github.com/pion/sctp/commit/e4e606d1fff223734f7aa74c50eb82d50932b3f4), is correctly packaged by the underlying `sctp` library and handed to goutils. That abort chunk error was being unnecessarily logged by both the data channel and negotiation channel.
[RSDK-3026]: https://viam.atlassian.net/browse/RSDK-3026?atlOrigin=eyJpIjoiNWRk …

RSDK-3026 Ignore and log user-initiated abort chunk

---

.github/workflows/test.yml
.gitignore
Makefile
etc/analyzecoverage/main.go
etc/analyzetests/main.go
etc/test.bash
go.mod
go.sum
tools/tools.go

The goutils repository can currently output code coverage data into a file that is slurped into a Github PR comment. This patch moves that code into test executaion rather than being contained as a github action. That change will result in an additional coverage file, `code-coverage-results.md` (gitignored) to be created in the goutils repo root when running `make cover`.

RSDK-906: Upload test result and coverage data into a MDB backend.

---

http2.go

We currently allow for weak ciphers in tls 1.2. This limits the ciphers to only the strong ones.

limit cipher suits

---

rpc/wrtc_client.go

After staring at this code for far too long, I think the only way the leak shown in RSDK-3286 could have happened was by this function returning via the select because of a race with other instances of itself. @edaniels Please take a look though, as I'm not 100% certain how this waitgroup pattern is supposed to function (deferring in a later anonymous function feels odd.)

[RSDK-3286] Fix go routine leak in wrtc ice candidate function

---

rpc/wrtc_signaling_answerer.go
rpc/wrtc_signaling_test.go
testutils/env.go

[RSDK-3441](https://viam.atlassian.net/browse/RSDK-3441)
Adds a mutex to keep `Start` and `Stop` exclusive for the signaling answerer. Adds a test to ensure `Start` and `Stop` do not race.
[TestWebStreamImmediateClose](https://github.com/viamrobotics/rdk/blob/main/robot/web/web_test.go#L789) is an rdk test I wrote that starts and immediately stops the web service to ensure there are no races/deadlocks. It occasionally (once every ~50 times) causes a [data race](https://github.com/viamrobotics/rdk/actions/runs/5180043576/jobs/9333712461) in goutils. The [signaling answerer’s](https://github.com/viamrobotics/rdk/blob/main/robot/web/web_test.go#L789) `Stop` method had a race with the signaling answerer’s `Start` method. The former tried to `Wait` for background workers and the latter tried …

RSDK-3441 Lock usage of Start and Stop for signaling answerer

---

rpc/wrtc_base_channel.go
rpc/wrtc_peer.go

[RDSK-3382](https://viam.atlassian.net/browse/RSDK-3382)
Removes `suppressing error from sctp` logs in both error callbacks (added in this [commit](https://github.com/viamrobotics/goutils/commit/f353bc8a72266afd24807a72d8470a92c8548fb8)).
The `DataChannel`'s `OnError` callbacks (like the `OnClose` callbacks) are [called](https://github.com/pion/webrtc/blob/c05e366e6677576c979a92d14d3cdeff660e34ab/datachannel.go#L346) asynchronously. This means they sometimes run while the channel is being closed or even slightly after. In our tests, this means they sometimes run while the testing object is being [marked](https://github.com/golang/go/blob/release-branch.go1.19/src/testing/testing.go#L1433) "done" and try to log something through the test logger, which …

RSDK-3382 Remove "suppressing" logs from error callbacks

---

rpc/client_interceptors.go
rpc/dialer.go
rpc/interceptors_test.go
rpc/server.go
rpc/server_interceptors.go
rpc/wrtc_client_channel.go
rpc/wrtc_server_stream.go

This PR fixes an issue in applications that use OpenCensus to maintain traces of spans which are spawned in distinct processes. Without this PR, when a client starts a span and initiates a gRPC request to a server which starts its own span, the server-side span will not mark the client-side span as its parent. This causes the trace to incorrectly report that the server-side span is unrelated to the client-side span.
This PR fixes that issue by adding the current SpanID, TraceID, and TraceOptions to the HTTP headers that are sent in every gRPC request from the client-side. When the server receives those headers, it extracts the span metadata and inserts it into the current context as a new span called `server_root`. Later spans created in the server logic will automatically be made …

RSDK-3476 Fix distributed logging

---

pexec/process.go
pexec/process_test.go

RSDK-3329
Caches errors from process config validation and adds an `Equals` function that ignores validation-related fields. Needed for https://github.com/viamrobotics/rdk/pull/2638.

RSDK-3329 Cache errors from process config validation

---

web/user.go

**20230625_APP-2028: Add get last login method**
- Extends the “UserInfo” struct with a new method, GetLastLogin.
- GetLastLogin is needed to help provide last login time of users for display in the members table of the org settings page.
Figma: https://www.figma.com/file/2hs9zGWN9nTLqcm8pR38ip/Management?type=design&node-id=3039-21808

APP-2028: Add get last login method

---

web/sessions.go

This is required for: [Create TTL index on web.sessions in app.viam](https://viam.atlassian.net/browse/APP-2535)
In this PR, I added code to ensure that a TTL index is created on the `web.sessions` collections as this helps me close out work on the `app.viam` on creating a TTL index that removes sessions documents that are over 30 days old.

APP-2534: Create a TTL index on the web.sessions collection

---

web/sessions.go

In this PR, I fixed the name of the TTL index created on the `web.sessions` in code from `lastUpdated` to `lastUpdate`

App 2534: Fix index naming

---

string.go

In 32-bit builds, RandomAlphaString can crash with 'index out of range'
Note: golang won't let you compile a simple `array[-1]` because it knows negative numbers shouldn't be array indices, but this sample will repro if you want to see the failure:
```go
package main
import "math"
import "math/big"
import "crypto/rand"
func main() {
arr := []int{1,2,3}
for i := 0; i < 20; i++ {
val, _ := rand.Int(rand.Reader, big.NewInt(math.MaxInt64))
index := int(val.Int64()) % len(arr)
println("index", index, "val", arr[index])
}
}
```
Then
```sh
GOARCH=386 go build main.go && main
```
(if you're on M1 mac, do GOARCH=arm)

RandomAlphaString fix for 32-bit

---

etc/.golangci.yaml
runtime.go
runtime_posix.go
runtime_windows.go

- move signal registration for ContextualMain to architecture-specific file
- note: I'm not sure what this is used for and it's possible ContextualMain won't work correctly on windows (but seems like SIGTERM will still support some use cases)
- this is for CLI, which doesn't use ContextualMain. another option here would be to move the entire ContextualMain logic to runtime_posix.go
- this is to allow a windows-specific build of the CLI in rdk repo

DATA-2031 windows-specific build

---

protoutils/protoutils.go
protoutils/protoutils_test.go

Hey yall, as part of queryable sensor data , we would like users to be able to see all fields of their data regardless of it is an "empty value". If a boolean is false, it can be dropped from the collector which is not ideal. The testing for the new method is fairly barebones as its fundamentally the same method, just added a case where it shouldn't be dropping a variable. I'm happy to add more if required.

Add struct to structpb method that ignores omit empty tags

---

.github/workflows/test.yml
pexec/managed_process.go
pexec/managed_process_test.go
pexec/managed_process_unix.go
pexec/managed_process_windows.go
pexec/process.go

- add Username in managedProcess + ProcessConfig
- when this field is present, managedProcess looks up the user and runs as them
- add a new CI step to test this (because it needs to run with setuid capability)
- to support running non-privileged subprocess (if necessary in the future)

add ProcessConfig.Username field

---

rpc/auth.go
rpc/auth_test.go
web/api.go

[Ticket](https://viam.atlassian.net/browse/APP-2592)
The goal of this PR is to add the `MakeSimpleMultiAuthPairHandler` which implements an auth handler for an api key and api key id pair. The goal is described more in-depth [here](https://docs.google.com/document/d/1o1Eq0bQBun4LADDaOWGjUTI9dfOnI4wenTe6JtChe3Y/edit#bookmark=id.ff76wzf60oxk)

APP-2592:  Goutils: implement auth handler that supports (id, key) pairs

---

rpc/wrtc_base_channel.go
rpc/wrtc_base_stream.go
rpc/wrtc_client_channel_test.go
rpc/wrtc_client_stream.go
rpc/wrtc_server_stream.go

Could be related to https://viam.atlassian.net/browse/RSDK-5235 and/or https://viam.atlassian.net/browse/RSDK-4473.
Cancels channel context when peer has finished (connection was closed, or connection state moved to disconnected, failed or closed). Respects channel context in base stream `RecvMsg`, so streams 
(both client and server) will not hang if connection gets closed mid-operation-invocation.

RSDK-4473 Make stream message reception sensitive to peer finishing

---

pexec/managed_process.go
pexec/managed_process_test.go
pexec/process.go

Ticket: https://viam.atlassian.net/browse/RSDK-5350
Blocks: https://github.com/viamrobotics/rdk/pull/3062
Hoping to get this into the release tomorrow morning. However, if that is not possible, that is okay.
Main question is whether this will work on windows. I haven't done any PRs to this repo yet so not sure if we have a good way to test that.

RSDK-5350 - Update goutils to support passing environment variables to managed processes

---

rpc/server.go
rpc/server_auth.go
rpc/server_auth_test.go

Allows the ability for usages of goutils to call EnsureAuth whenever auth checks are needed that don't follow the convention of RPC Credential Type (For example checks outside of gRPC calls).

APP-2890: Refactor to make EnsureAuth Public

---

rpc/server_test.go
rpc/wrtc_client.go
rpc/wrtc_signaling_answerer.go

Wait on all goroutines related to ice candidate negotiation to complete before closing the server.
Testing
- goleak reproduced in [this commit](https://github.com/viamrobotics/goutils/pull/211/commits/9e03120cf4087b105d7d62ae022c5a24a6a3cf0e)

RSDK-4293 wait for answerer to finish completely

---

rpc/examples/echo/frontend/package-lock.json
rpc/js/package-lock.json
rpc/js/package.json
rpc/js/src/dial.d.ts
rpc/js/src/dial.ts
rpc/js/src/peer.d.ts
rpc/js/src/peer.ts

[Related TS SDK change](https://github.com/viamrobotics/viam-typescript-sdk/pull/181)
[Jira ticket](https://viam.atlassian.net/browse/RSDK-5228)
Allowing for a custom priority attribute to be pushed in.
Tested with a board running the MicroRDK to confirm default and customized priority works as expected. Also tested with a robot running the regular RDK (with and without a priority attribute) to confirm everything else still works. The echo example was also run to confirm it ran smoothly.

RSDK-4952 - pass priority attribute

---

rpc/examples/echo/frontend/package-lock.json
rpc/js/package-lock.json
rpc/js/package.json

Bumping the version here so we can get the typings issues that were fixed as a transient dependency in `@viamrobotics/sdk` and ultimately `app`.
See my PR for the downstream issue: https://github.com/viamrobotics/app/actions/runs/6895151896/job/18758485918?pr=2866

Bump @viamrobotics/rpc to 0.1.39

---

.github/workflows/test.yml

Cribbed from [the rdk](https://github.com/viamrobotics/rdk/blob/e92959d049e72b0ed57c1dcb9a2328ee5160d802/.github/workflows/test.yml#L84-L90).
Claim that `test.json` is the file to upload:
* The [test command](https://github.com/viamrobotics/goutils/blob/39728ac2cfd339fc555eb547ca71e4ab59bf05bb/.github/workflows/test.yml#L77-L84) calls `make cover`
* [`make cover` calls `etc/test.bash`](https://github.com/viamrobotics/goutils/blob/39728ac2cfd339fc555eb547ca71e4ab59bf05bb/Makefile#L59-L60)
* [`test.bash` calls `gotestsum` with `--jsonfile json.log`](https://github.com/viamrobotics/goutils/blob/39728ac2cfd339fc555eb547ca71e4ab59bf05bb/etc/test.bash#L12)

RSDK-5906: Upload CI test.json file as a github artifact.

---

etc/analyzetests/main.go

- increase connection timeout from 5 seconds to 10 seconds
Intermittent failures like this one:
https://github.com/viamrobotics/app/actions/runs/7024504474/job/19113759522?pr=3012#step:6:7464
> 2023-11-28T21:20:07.524Z	FATAL	analyzetests	utils@v0.1.52/runtime.go:78	timed out while checking out a connection from connection pool: context deadline exceeded; maxPoolSize: 100, connections in use by cursors: 0, connections in use by transactions: 0, connections in use by other operations: 1

RSDK-6097 increase analyzetests connection timeout

---

rpc/wrtc_call_queue_mongodb.go

Hey yall, this PR is just to add more logging to the warning when we get the all answerers are too busy case in goutils. Once this is approved, Ill bump the version in app and put up another PR for that. Thank you!

APP-3488 Add logging to callAnswererTooBusy warning.

---

rpc/examples/echo/frontend/package-lock.json
rpc/js/package-lock.json
rpc/js/package.json
rpc/js/src/dial.ts
rpc/js/src/main.ts

`@viamrobotics/rpc@0.2.0` is not consumable by `@viamrobotics/typescript-sdk` because the typescript SDK imports a few interfaces directly from the `src` directory. This is no longer possible in the `v0.2.0` release because:
- It adheres to latest JS publishing best practices and does not allow importing anything other than the explicitly exported distributable files.
- The TypeScript SDK does this in two places. In one place, it's a typo. In the other place, it's because a necessary type interface is not exported by RPC.
- We accidentally forgot to include `.d.ts` files in the build step!
- This used to be handled by webpack, but is not handled by vite, so we need to call `tsc` ourselves now
- Add all interfaces that are arguments or return values (or deeply included in those interfaces) …

RSDK-5407: fix RPC web build and add missing public exports

---

rpc/wrtc_call_queue_mongodb.go

Hey yall, this PR is to add logging to the send method to determine what case it's hitting when it returns false. For now I just included the whole event with the intention of backing this out once we get to the root of this issue. I also added a log for how many answer channels there are as I realized in only logging on the warning, we don't know if only having 1 answer channel is normal or not.

APP-2747 Add logging to send for debugging

---

rpc/wrtc_call_queue_mongodb.go

Hey yall, this PR is to add the hostname to our metric for call answerers too busy. This will allow us to filter by host in the metric explorer so we can breakdown what robot are causing what errors more easily.

APP-2747 Add hostname to metric

---

rpc/js/src/dial.ts

Fixes an issue where we were attempting to use a metadata object before it was initialized.

Move metadata initialization before usage

---

rpc/wrtc_peer.go

[RSDK-239](https://viam.atlassian.net/browse/RSDK-239)
[RSDK-6343](https://viam.atlassian.net/browse/RSDK-6343)
When using something like tailscale (also reportedly happens from within certain docker images), it is sometimes the case that a WebRTC agent will propose an ICE candidate with an IPV6 address. While Viam does not support IPV6, we were not explicitly disallowing IPV6 ICE candidates to be elected in our Golang connections. This caused odd hangs in `RecvMsg` when connecting to remotes through tailscale.
The issue really only presented itself when a main robot had a stream to a remote robot. I was able to repro the error with a Mac on tailscale on network 1 listing a remote of a Linux machine on tailscale on network 2 with a webcam. When the wifi on the Mac was turned off and on …

RSDK-239 RSDK-6343 Disallow IPV6 connections

---

.github/workflows/test.yml
rpc/dial.go
rpc/doc.go

Update dial logic to attempt mDNS and WebRTC connections in parallel.
I ran a script that dials a robot 20 times using the current (serial) and newly implemented (parallel) dial logic. I ran this comparison under two network conditions:
* **hotspot -> viam**: Client and server on different networks, so mDNS will always fail.
* **viam -> viam**: Client and server on the same network, so mDNS may succeed.
Here are the results (in seconds):
| | Serial Hotspot->Viam | Parallel Hotspot->Viam | Serial Viam->Viam | Parallel Viam->Viam |
|------------|----------------------|------------------------|-------------------|---------------------|
| Avg        |                 5.28 |                   2.67 |              1.99 |                1.30 |
| Stdev      |                 1.30 | …

RSDK-6151 parallel mDNS / WebRTC dials

---

rpc/examples/echo/frontend/package-lock.json
rpc/js/package-lock.json
rpc/js/package.json
rpc/js/src/BaseChannel.ts
rpc/js/src/dial.ts

adding dial timeout lets us give up on failed connection attempts faster, shouldn't matter too much for fast connections, but 95% time is a lot faster (on app, which auto redials)
tested by linking the libraries together, so checked that the dialTimeout option actually works
data collected doesn't show the value of the change very well, but from previous anecdotal data, any connection that fails on the first try will take 20s, but with the new change it would be closer to 8-9s (since first failures usually take 15s or so)
| Attempt | With Change (# fails) | Without Change (# fails) |
|---------|-----------------------|--------------------------|
| 1       | 9.5 (1)               | 30.07                    |
| 2       | 4.61                  | 3                        |
| 3       | 1.591 …

RSDK-6041 - Add dial timeout to ts 

---

rpc/examples/echo/frontend/package-lock.json
rpc/js/package-lock.json
rpc/js/package.json
rpc/js/src/BaseChannel.ts
rpc/js/src/ClientChannel.ts
rpc/js/src/dial.ts
rpc/js/src/main.ts
rpc/js/src/peer.ts
rpc/js/src/polyfills.ts
rpc/js/vite.config.ts

This PR enables the RPC library to be used within React Native settings. The major changes required are:
* Allowing a configuration for a non-browser `grpc.TransportFactory`
* The user can specify a new `TransportFactory` by setting the global variable `global.VIAM.GRPC_TRANSPORT_FACTORY`
* This library will default to the cross-browser transport
* Polyfill `atob` and `btoa` because those aren't available outside of browser environments
* Change all the `on{EVENT}` functions to `addEventListener({EVENT})` to work with both browser and React Native

Enable React Native

---

.github/workflows/proto-checks.yml

The `proto-checks` workflow failed because of a rate limit exception (see [this run](https://github.com/viamrobotics/goutils/actions/runs/8143607497/job/22255828000))
This PR should hopefully fix it. Also migrates away from a self-hosted runner

Add github token

---

rpc/wrtc_server.go
rpc/wrtc_server_stream.go

RSDK-1687
Changes `wrtc_server.go` and `wrtc_server_stream.go` logic:
- Renames `mu` to `peerConnsMu`.
- Renames `activeBackgroundWorkers` to `processHeadersWorkers`.
- Adds a `processHeadersMu` to guard it
- `RLock`s the `processHeadersMu` when `Add`ing to `processHeadersWorkers`
- `Lock`s the `processHeadersMu` when `Wait`ing on `processHeadersWorkers`
The linked ticket describes a data race where `activeBackgroundWorkers.Add(1)` was racing with `activeBackgroundWorkers.Wait()`. This was happening because the `Add` was in a separate goroutine from the `Wait` due to the asynchronous nature of WebRTC "callbacks", and there was no synchronization of `Add`s and `Wait`s.
cc @viamrobotics/netcode .

RSDK-1687 Better synchronize `Stop` and `processHeaders`

---

pexec/managed_process.go
pexec/managed_process_test.go
pexec/managed_process_windows.go

This change allows managed processes to check if their process is still running.
~This method (and the underlying Signal call from golang stdlib) is not supported on windows.~
Correction: Signal Interrupt is not supported on windows

[RSDK-6030] add Status() to ManagedProcess

---

rpc/wrtc_signaling_answerer.go

RSDK-5534
Better synchronize active goroutines in `wrtc_signaling_answerer.go`. Very similar to change in https://github.com/viamrobotics/goutils/pull/251.
- Renames `activeBackgroundWorkers` to `answerWorkers`
- Renames `cancelBackgroundWorkers` to `cancelAnswerWorkers`
- Adds an `answerMu` `RWMutex` to be `RLock`ed when adding an answer worker and `Lock`ed when waiting on answer workers
The linked ticket describes a data race where `activeBackgroundWorkers.Add(1)` was racing with `activeBackgroundWorkers.Wait()`. This was happening because the `Add` was in a separate goroutine from the `Wait` due to the asynchronous nature of our answering process, and there was no synchronization of `Add`s and `Wait`s.

RSDK-5534 Better synchronize answer workers

---

rpc/server_auth.go

Accidentally copy-pasted a return where we should not be returning, only logging.
Fixes [this issue](https://viaminc.slack.com/archives/C01Q5S8V6TB/p1710689886947519).

Remove bad return value

---

pexec/managed_process.go
pexec/managed_process_test.go
testutils/file.go

If current working directory (CWD) is provided, make sure it exists before starting the managed process. If it doesn't or there is some other error related to looking up the CWD, return a more descriptive error.

RSDK-6130 Improve error message if CWD of process does not exist

---

pexec/managed_process_test.go
pexec/process_manager_test.go
testutils/file.go

Follow-up to https://github.com/viamrobotics/goutils/pull/276 - I noticed we have a bunch of boilerplate setup/tear-down code around creating temp files and watchers - this PR encapsulates these procedures into helpers.

Improve test utilities for temp file and file watcher creation

---

rpc/client_interceptors.go
rpc/dialer.go
rpc/dialer_test.go
rpc/server.go
rpc/server_auth.go
rpc/server_options.go

RSDK-7010
Adds a unary client interceptor to clear the `accessToken` set on `perRPCJWTCredentials` in the event of an error containing the substring `"Unauthenticated"`. Clearing the `accessToken` causes an attempt to reauthenticate on the next RPC request. Adds a test for this behavior.

RSDK-7010 Invalidate JWT access token upon Unauthenticated error

---

rpc/wrtc_call_queue_mongodb.go

[RSDK-7311](https://viam.atlassian.net/browse/RSDK-7311)
Adds an extra filter to the MDB call queue's `UpdateOne` that ensures the given `calls` document has not already been answered.
Signaling answerers run two goroutines (up to `defaultMaxAnswerers`) that both open bidi [`Answer`](https://github.com/viamrobotics/goutils/blob/main/proto/rpc/webrtc/v1/signaling.proto#L41) streams against the signaling server. The signaling server waits on `RecvOffer` from its call queue implementation (`wrtc_call_queue_mongodb.go` in prod) for both of these calls. It could be the case (and seemingly often was in my testing) that 
1. The first `RecvOffer` would run `FindOneAndUpdate` to mark the `calls` document as `answered` and send an `AnswerRequest_Init` back to one of the signaling answerer …

RSDK-7311 Fix MDB call queue `UpdateOne`

---

.github/workflows/buf.yml
.github/workflows/license_finder.yml
.github/workflows/publish.yml

- remove four `qemu-host` tags across 3 workflows
- these jobs don't require emulation

move workflows to hosted

---

web/auth0.go

When there is no cookie present, redirect back to login. The application should then request authentication flow again. In most cases the user will already be logged in and see nothing. This just add another redirect. In other cases the user will need to login again if the auth provider cannot validate the state and cookies.

APP-3746: Redirect to login when no auth cookie present

---

rpc/examples/echo/frontend/package-lock.json
rpc/js/package-lock.json
rpc/js/package.json
rpc/js/src/dial.ts

RSDK-7244 describes how the TS SDK does not attempt reconnect when a disconnect occurs.
The TS SDK attempts to reconnect to the peer in a [backoff loop](https://github.com/viamrobotics/viam-typescript-sdk/blob/f49f6857de9277f72f1e4894b985ea976ae51ea0/src/robot/client.ts#L186). This happens whenever a [disconnect event](https://github.com/viamrobotics/viam-typescript-sdk/blob/f49f6857de9277f72f1e4894b985ea976ae51ea0/src/robot/client.ts#L177) occurs.
The TS SDK currently listens to `iceconnectionstatechange` `close` events on the `RTCPeerConnection` to [emit the disconnect](https://github.com/viamrobotics/viam-typescript-sdk/blob/f49f6857de9277f72f1e4894b985ea976ae51ea0/src/robot/client.ts#L469-L483) necessary to start the reconnection. These events are never being emitted, as confirmed …

RSDK-7244: Expose data channel so TS SDK can listen for disconnect

---

leak.go

Once this is in and tagged I'll create an RDK PR that:
* Bumps goutils
* Removes the wait on the "on close" channel from module/shared conn closing.
cc @benjirewis for visibility

RSDK-7691: Exempt `DataChannel.readLoop` from leak detection.

---

go.mod
go.sum

[Ticket](https://viam.atlassian.net/browse/RSDK-7637)
This Pion patch fixes the issue linked in the ticket: https://github.com/pion/webrtc/commit/43a6a6996bff40982aa2d43a354da7325db8a558 
Deps changed:
https://github.com/pion/webrtc/compare/v3.2.36...v3.2.42
https://github.com/pion/ice/compare/v2.3.13...v2.3.24
https://github.com/pion/sctp/compare/v1.8.14...v1.8.16

RSDK-7637 - bump pion from v3.2.36 to v3.2.42

---

rpc/wrtc_client_channel_test.go
rpc/wrtc_client_stream.go

actual code change is tiny - risk should be low as well since reset stream is only ever called when context is cancelled and in that case, the request should be cancelled anyway

RSDK-7678 - Server streaming does not obey context cancels over WebRTC

---

rpc/wrtc_base_channel.go
rpc/wrtc_base_channel_test.go
rpc/wrtc_client.go
rpc/wrtc_client_channel.go
rpc/wrtc_client_channel_test.go
rpc/wrtc_server_channel.go
rpc/wrtc_server_channel_test.go

RSDK-7280
Logs:
- When/which local ICE candidates are gathered
- When/which remote ICE candidates are received
- How long from start of `dialWebRTC` to ICE connection state of connected
- Number of caller updates in that time
- Average duration of caller updates in that time
- Max duration of caller updates in that time

RSDK-7280 Report more ICE timings

---

go.mod
go.sum

Reverts viamrobotics/goutils#292
A Pion user commented on the [GitHub issue](https://github.com/pion/webrtc/issues/2774#issuecomment-2186475736) that lead to the[ attempted OnTrack not firing fix ](https://github.com/pion/webrtc/commit/43a6a6996bff40982aa2d43a354da7325db8a558) that went into v3.2.42 of pion/webrtc that it introduced a regression.
While we have not yet detected a regression in viam software, out of an abundance of caution, we should roll back to the last stable version of pion/webrtc & not rely on a version with a known regression.

Revert "RSDK-7637 - bump pion from v3.2.36 to v3.2.42"

---

rpc/wrtc_signaling_test.go

Description:
We had observed a datarace in the test `TestWebRTCAnswererImmediateStop` that resulted in an attempt to write logs after completion of the test. To fix this, we wait on the running goroutines to complete before closing the test.

RSDK-6659: wait on running goroutines before concluding test

---

rpc/wrtc_client.go

Do not report stats if no call updates were captured (avoid divide-by-zero).

Avoid division-by-zero in stats reporting

---

rpc/wrtc_server_stream.go
rpc/wrtc_server_stream_test.go

if we call SetHeader and SendHeader at the same time, there's a chance at a datarace. Adding the RLock removes that possibility. The grpc-go impl has specific [locks](https://github.com/grpc/grpc-go/blob/f199062ef31ddda54152e1ca5e3d15fb63903dc3/internal/transport/transport.go#L469) for the header, but not sure if it's necessary. The main call into writeHeader already holds the RLock anyway (https://github.com/viamrobotics/goutils/blob/59474fccb894a0593029792c977ffb9bd173a4aa/rpc/wrtc_server_stream.go#L169).
Able to reproduce with a test that ran SetHeader and SendHeader side-by-side, and confirms that the race went away with this fix. Did not add that test into this PR because it's flaky

RSDK-7935 - Fix header datarace

---

rpc/dialer.go

So on macOS, changing network interfaces does not appear to be an issue, but it is on Linux. As James pointed out, when you switch, it can take a very long time to have the gRPC connection start using the new network interface. This issue is further compounded by the cached gRPC dialer that rdk uses for app.viam.com based connections. Adding a keep alive solves the issue (by default it's not used) since once the keep alive is sent and enough are not ACKd, the http2 client transport is closed, the internal client load balancer sees this, and makes a new connection using a suitable interface that has a valid gateway.

RSDK-7936 - grpc: set keepalive to handle network interface changes

---

rpc/const.go
rpc/dialer.go
rpc/server.go

Adding the server side params eliminates the GOAWAY errors coming from the internal signaling server (tested by running a local config in RDK for 20 mins), TBD as to whether it'll stop errors coming from cloud connections (so far, I've seen reduced rates, but usually some pop up after 8 mins). There's a possibility that after pushing this change to app, this log will go away as well, but possible that app load balancer may continue to issue these errors.
We could also look into filtering that specific log out, since there's no real issue as far as we can tell

RSDK-8215 - Decrease amount of GOAWAY errors

---

rpc/js/src/dial.ts

There is a bizarre little issue where `viam-server`, even on latest, is giving `Unimplemented` errors when calling `OptionalWebRTCConfig` in some typescript tests. I've spent a decent amount of time trying to decipher why and failing to do so; the problem only exists in typescript. However, defaulting to returning an empty config when an `Unimplemented` error is received allows tests to run as expected. 
Note that there is precedent for us doing this; currently an analogous piece of logic exists in `rust-utils`.

RSDK-7647 - fallback to empty webrtc config when method is unimplemented

---

logger.go
logger_test.go
pexec/managed_process.go
rpc/server.go
rpc/wrtc_client.go
rpc/wrtc_logger.go

RSDK-8320: Allow RDK loggers to call sublogger when creating new loggers in goutils
* We are unable to maintain any pointers to loggers created by `Named()`. Now that RDK loggers can be passed into goutils without any conversion, we can create and register new loggers in `goutils` by calling `Sublogger()`.
* `goutils` still needs to be compatible with the Zap logging interface because of `app`. In order to allow RDK loggers to call `Sublogger()` a `utils.Sublogger()` function is added in this PR which uses reflection to either call `Sublogger()` if it is an RDK logger, or `Named()` if it is a Zap logger. 
* This way, when RDK loggers are passed into `goutils`, `Sublogger()` is called registering these new loggers. 
* Replaces all instances of `Named()` in `goutils` with …

RSDK-8320: Allow RDK Loggers to Call Sublogger()

---

rpc/dial_test.go
rpc/wrtc_signaling_answerer.go

mostly a prefactor so that it will be easier to refactor to use a passed in connection later on.
main behavior change is that the reconnect logic got tossed, idea being that any direct grpc connections will reconnect on their own anyway
Tested a few cases to ensure no regressions and confirmed that we can connect to the robot through WebRTC
* Long idle connection (over 1hr)
* Switching network interfaces (changing wifis/to my phone hotspot)
* Losing internet
Also ran tests with RDK to ensure those still passed

RSDK-8265 - Share connection in signaling answerer

---

pexec/managed_process.go
pexec/managed_process_test.go

Ticket: https://viam.atlassian.net/browse/RSDK-8287
See ticket for more information

RSDK-8287 - ManagedProcess fails on relative executable paths with a modified CWD

---

rpc/wrtc_client.go
rpc/wrtc_signaling_answerer.go

RSDK-8288: Make caller and answerer less sensitive to errors from signaling server
* Signaling caller and answerer are made less sensitive to signaling server errors by swallowing either `io.EOF` errors or grpc errors of the type `code = Internal desc = unexpected EOF` and logging it. 
* This is necessary since after one of the answerer/caller calls `sendDone()` and severs its connection to the signaling server, it is possible that the other has not had the chance to "finish" and timing can cause it to get a EOF error from its connection to the signaling server, causing the peer connection to be unecessarily closed.

RSDK-8288: Make caller and answerer less sensitive to errors from signaling server

---

logger.go
logger_test.go
rpc/wrtc_base_channel.go
rpc/wrtc_call_queue_mongodb.go
rpc/wrtc_client_channel.go
rpc/wrtc_server_channel.go
rpc/wrtc_server_stream.go

RSDK-8377: Allow RDK to maintain track of Loggers that call With()
* Adds `LogWith()` util function that calls `With()` on `zap.SugaredLoggers` and `WithField()` on RDK loggers using reflection so that we do not lose track of RDK loggers that call `With()` in `goutils`.
* Change all instances of `With()` to `utils.LogWith()`
* A few tests to ensure that the correct one of `With()` / `WithField()` is called depending on the type of logger.

RSDK-8377: Allow RDK to maintain track of Loggers that call With()

---

logger.go
rpc/server.go
rpc/wrtc_server_stream.go

RSDK-8404: Add logging around incoming GRPC requests.
Also, RDK logger `WithFields()` now returns a new logger instead of a modifying the current logger, so this function needed a small refactor to account for that

RSDK-8404: Add logging around incoming GRPC requests + Refactor AddFieldsToLogger function to account for new logger type

---

stoppable_workers.go
stoppable_workers_test.go

Having it in RDK also bit me again today: during 20% Happy Hour, I tried using it in the `logging` package, but introduced a circular dependency (logging would import utils, which imports logging). I haven't needed to tweak the implementation in months; I think this is ready for goutils!
The linter and compiler are happy. I haven't tried this copy out more than that, but the first commit is a byte-for-byte copy of the widely-used version in RDK, and then the second commit is adapting it for goutils.
Benji thought we could get rid of the interface/struct split, and I'm open to such a change, though don't see how to do it myself. but in the meantime, here's the start.

[RSDK-8570] Add StoppableWorkers from RDK

---

.github/workflows/license_finder.yml
go.mod
logger.go

- bump min golang in go.mod to 1.21.13
- (incidental) change base image of license_finder job so it gets newer license_finder which can handle new go.mod syntax
- (incidental) add `nolint:wastedassign` for defer/recover pattern -- someone who understands intent here should review to make sure this is still needed
netip vuln https://pkg.go.dev/vuln/GO-2024-2887

bump min golang

---

.github/workflows/publish.yml

- switch base image from canon -> rdk-devenv
My previous PR #339 used a 3-part go version which broke parsing. Failed run [here](https://github.com/viamrobotics/goutils/actions/runs/10723655924).

update base image for publish flow

---

.github/workflows/test.yml

- switch order of steps so setup-go has access to go.sum from the checkout
caching / perf (save time spent downloading)
:heavy_check_mark:  https://github.com/viamrobotics/goutils/actions/runs/10729087347

use setup-go caching in test.yml

---

rpc/server_auth.go
rpc/server_auth_test.go

this has been an existing bug for at least a few years - we get the server panic but as long as we close down properly the error actually gets lost as streamClients don't error even if the server side definitely did, the error only shows up after we try to receive the message.

RSDK-8480 - Actually pass server impl into auth stream handler

---

rpc/const.go
rpc/dialer.go
rpc/wrtc_client.go
rpc/wrtc_peer.go
rpc/wrtc_signaling.go
rpc/wrtc_signaling_answerer.go

[RSDK-8545](https://viam.atlassian.net/browse/RSDK-8545)
Makes dialing and ICE code sensitive to the `SOCKS_PROXY` environment variable. This variable will be set by viam-agent and indicates the address of the rust proxy through which the RDK should forward its network traffic.
This is a tough one to write unit tests for. I can do it if reviewers wish, but the tests may end up strawman-esque in the sense that I would need a full integration test to ensure routing through a SOCKS proxy "works". The manual testing I have done is to:
1. Run the [grill proxy](https://github.com/viam-labs/ble-managed/tree/main/grill_proxy) on a rock4
2. Run the [flutter proxy](https://github.com/viam-labs/ble-managed/tree/main/phone_proxy) on an iPhone
3. Run the RDK on the same rock4 with `VIAM_SOCKS_PROXY` …

RSDK-8545 Leverage SOCKS proxy for direct dialing and ICE

---

mongo/namespace.go

Our tests in `app` call setup utils via `backingMongoDBURI`  which eventually sets up randomized namespaces for out DBs. We sometimes run into an issue with testing in which the random portion of the names for the test databases have the same characters but in different casing which results in a cascade of test failures. The quick solution is to lengthen the random portion and then lowercase it (should at least prevent the mixed-case error). If I remember correctly, if the name is exactly the same, there is logic to handle that?
@dgottlieb I believe we talked about this a while ago briefly, but figured I'd get your eyes!

[APP-5672] lowercase and lengthen random string to mitigate name collision

---

stoppable_workers.go
stoppable_workers_test.go

I like the idea of having a `NextTick` for my worker. But I think there are some oddities with this so floating it around first.
We should chat about what our options are here as a next step.

RSDK-8802: Add StoppableWorkers.StartTimer/NextTick.

---

stoppable_workers.go

See discussion at https://github.com/viamrobotics/goutils/pull/353/files#r1777286836. I also put in a comment on a part I wished had a comment in it. :wink: Without it, my first instinct is to go back to using `defer sw.mu.Unlock()` immediately after locking it.

Bugfix: unlock mutex before returning

---

rpc/const.go
rpc/dialer.go
rpc/wrtc_peer.go
rpc/wrtc_signaling_answerer.go

`socksProxyEnvVar` -> `SocksProxyEnvVar`. Planning on accessing the value from `rdk` and `agent` to bump some networking timeouts when we are behind a SOCKS proxy.

Export SocksProxyEnvVar

---

rpc/dialer.go

cc @viamrobotics/netcode ; forgot to exclude addresses starting with `unix` when behind SOCKS proxies.

Do not connect to unix-schemed URIs through SOCKS proxy

---

testutils/mongodb.go

Now that the `TEST_MONGODB_URI` env var has been updated, we do not have to skip MDB tests.

RSDK-8952 Stop skipping MDB tests

---

testutils/ext/verify.go

I was getting errors like this pretty often:
```bash
> go test -tags=cse -run=TestTabularDataCaptureUploadS3 -race
PASS
goleak: Errors on successful test run: found unexpected goroutines:
[Goroutine 5 in state IO wait, with internal/poll.runtime_pollWait on top of the stack:
internal/poll.runtime_pollWait(0x104594ca0, 0x77)
/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/netpoll.go:345 +0xa0
internal/poll.(*pollDesc).wait(0xc0000e69a0, 0x77, 0x0)
/opt/homebrew/Cellar/go/1.22.2/libexec/src/internal/poll/fd_poll_runtime.go:84 +0xb8
internal/poll.(*pollDesc).waitWrite(...)
/opt/homebrew/Cellar/go/1.22.2/libexec/src/internal/poll/fd_poll_runtime.go:93
internal/poll.(*FD).WaitWrite(...)
/opt/homebrew/Cellar/go/1.22.2/libexec/src/internal/poll/fd_unix.go:683 …
```

DATA-2663 - Reduce goroutine leaks while running local tests

---

logger.go
logger_test.go

https://viam.atlassian.net/browse/RSDK-9159 is logged, I don't think it makes sense to give devs a false sense that zap loggers will work with the current implementation.

Make clear AddFieldsToLogger only works for RDK loggers

---

web/auth.go

Quick fix: It looks like paths were not throwing an error, so I added a check to ensure a valid URL does not have a hostname. This should restrict it to just internal paths. Tested and this resolves the issue we were seeing with e2e tests in app trying to bump the goutils version.

Fix backto check

---

duration.go
duration_test.go
testdata/fuzz/FuzzDurationJSONRoundtrip/771e938e4458e983

Pulled out from https://github.com/viamrobotics/rdk/pull/4511
Create a custom `Duration` type that can be JSON marshaled/unmarshaled.

Add JSON-marshalable duration

---

pexec/managed_process.go
rpc/wrtc_base_channel.go
rpc/wrtc_signaling_answerer.go

Quiets and removes some logs per SE feedback.
cc @viamrobotics/netcode

Quieter signaling and module logs

---

rpc/wrtc_client_channel.go
rpc/wrtc_client_stream.go
rpc/wrtc_client_test.go

RSDK-9316
Checks the underlying channel's context for error before creating a new client stream. Returns a new `ErrDisconnected` error if the context has errored. A PR like [this one](https://github.com/viamrobotics/rdk/pull/4571) would make `rdk` sensitive to that new error instead of just waiting for `io.ErrClosedPipe` after an eventual read/write (?) from/to the closed channel.
Confirmed that this PR plus the linked `rdk` one gets rid of the race seen in https://github.com/viamrobotics/rdk/pull/4566 CI.

RSDK-9316 Disallow client stream creation when channel has been closed

---

perf/exporters.go

Will hopefully resolve the following [logs](https://console.cloud.google.com/logs/query;query=SEARCH%2528%22buffer%20full%22%2529;cursorTimestamp=2024-12-18T21:51:16.142767Z;duration=P7D?invt=AbkdmQ&project=web-app-304613): `OpenCensus Stackdriver exporter: failed to upload 10606 spans: buffer full`

DATA-3594 Bump up StackDriver exporter TraceSpansBufferMaxBytes

---

pexec/managed_process.go
pexec/managed_process_test.go
pexec/managed_process_unix.go
pexec/managed_process_windows.go

This is part one of two PRs that will hopefully help with shutting down all module processes before viam-server exits. Part 2 is [here](https://github.com/viamrobotics/rdk/pull/4657)
This is still a draft as I'm looking for thoughts and ideas around making this better. 
The idea behind this is for a Kill() call to propagate from the viam-server, and we should not block on anything if possible. The `kill()`s here do not wait for the execed process to complete, and this is intentional - I couldn't find if syscall.Kill waits for completion, so did not use. I wasn't able to find documentation about whether `kill -9` blocks on the signal getting received or if it immediately returns, so opted for `.Start()` instead of `.Run()`, which means we do not `Wait()` for the process to return. This …

RSDK-9591 - Add KillGroup to ManagedProcess

---

rpc/server.go
rpc/server_options.go

#405 Previously introduced  a test failure in RDK due to a leaked Goroutine. The fix - put up in the same PR - was to _always_ use GracefulStop() when closing the gRPC server. [This](https://github.com/viamrobotics/rdk/actions/runs/12893598036/job/35950351518) is causing other tests (see the output logs [here](https://productionresultssa11.blob.core.windows.net/actions-results/69f42cfc-c1a1-452c-8d3c-9af145d8ca2a/workflow-job-run-73abc5b6-187b-537c-12c8-c5e31d8f6e33/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-01-21T19%3A24%3A16Z&sig=MY4emUZn%2BpWjmGM%2BrQ3fARPQcaqLgQOqJaah6ZbsmlQ%3D&ske=2025-01-22T05%3A45%3A19Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-01-21T17%3A45%3A19Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2025-01-21T19%3A14 …

[RSDK-9149] Default gRPC Server to 'Wait For Handlers'

---

rpc/server_interceptors.go
rpc/wrtc_server_stream.go

used to look like
```
2025-01-24T17:53:02.436Z        ERROR   rdk.networking  goutils-cheuk/logger.go:161  finished unary call with code InvalidArgument   {"error":"rpc error: code = InvalidArgument desc = host not preconfigured","grpc.code":"InvalidArgument","grpc.time_ms":0.078,"grpc.start_time":"2025-01-24T17:53:02.436Z"}
```
and now it looks like
```
2025-01-24T17:57:09.728Z        ERROR   rdk.networking  goutils-cheuk/logger.go:161  finished unary call with code InvalidArgument   {"error":"rpc error: code = InvalidArgument desc = host not preconfigured","grpc.code":"InvalidArgument","grpc.time_ms":0.091,"grpc.start_time":"2025-01-24T17:57:09.727Z","grpc.request.deadline":"2025-01-24T17:57:19.722Z","span.kind":"server","system":"grpc","grpc.service":"proto.rpc.webrtc.v1.SignalingServic …
```

Add back missing fields in server logs and remove double log

---

rpc/wrtc_call_queue_memory.go
rpc/wrtc_call_queue_mongodb.go
rpc/wrtc_server.go
rpc/wrtc_server_channel.go
rpc/wrtc_server_stream.go

_**WIP**_
This PR is a continuation of #402 re: [this](https://github.com/viamrobotics/goutils/pull/402#pullrequestreview-2553454718) comment from @benjirewis (i.e., it updates `rpc/wrtc_server.go`, `rpc/wrtc_call_queue_memory.go`, and `rpc/wrtc_call_queue_mongodb.go` to use `StoppableWorkers` - and some other files as a side effect).

[RSDK-8666] Use Stoppable Workers

---

rpc/dial_options.go
rpc/server.go
rpc/wrtc_signaling_answerer.go

This PR allows for a preexisting connection to be passed to the constructor for our WebRTC signaling answerer to use via a dial option.
**Testing**
4 cases:
@cheukt and I ran the first tests by running viam-server on my laptop while connected to the Viam-Guest WiFi. He ran a client Go script on his laptop connected to the Viam WiFi. The client was able to connect to the robot via WebRTC both times.
1. client on different network can connect if rdk starts up offline then online (force webrtc option)
2. client on different network can connect if rdk starts up online then goes offline then online (force webrtc option)
3. client on same network can connect if rdk starts up offline then online (force webrtc option, but using the internal signaler)
4. client on same network can connect if rdk …

[RSDK-8293] Pass in Connection to Answerer in WebRTC Server

---

retry.go
retry_test.go

Talked with Benji offline -- he did not know of any wrapper that does this. I suspect we have duplicates of this littered around our codebase.
Needs tests. Will add tests after I confirm that:
a) We want to do this
b) This doesn't already exist somewhere in our codebase or in golang
I didn't put too much time into this. If we don't like this, I'll just implement retires as a one-off around my function in app.

Add error-retrying wrapper, RetryNTimes

---

retry.go

https://viam.atlassian.net/browse/RSDK-10229
`TestRetryNTimes/retry_with_context_cancelation` relied on `context.Canceled` consistently bubbling up as the error on the Nth retry when the N-1th caused a context cancelation. Without the check I added, the select on (now) L51 could randomly select `<-time.After(retryDelay)` despite `<-ctx.Done()` also being ready. Caused the test to fail ~10% of the time.
Mostly a testing fix, but _slightly_ better to return a context error without starting the loop again whenever one is available _before_ the `select`.

RSDK-10229 Add extra context check to RetryNTimes

---

rpc/const.go
rpc/dialer.go

this change will make SOCKS proxy a fallback option (if SocksProxyEnvVar is specified), but will not actively replace a connection if it is already established. If OnlySocksProxyEnvVar is specified, only the SOCKS connection is used.
It adds a small delay to the SOCKs dialer as a way to prioritize a connection made without the SOCKS dialer.
Conceptually, pretty similar to our Dial code and it borrows heavily from the net.DialContext code.
tested a few scenarios:
* only SOCKS initially, then a network blip and turn on both phone proxy and wifi (wifi connected in the end)
* only wifi initially, then a network blip and turn on both phone proxy  and wifi (wifi connected in the end)
* wifi and SOCKS initially, then a network blip and only turn on phone proxy (SOCKS connected in the end)
* wifi …

RSDK-9990- Expose SOCKS proxy as fallback dialer

---

pexec/managed_process.go
pexec/process.go

Allow specifying STDOUT and STDERR loggers through the process config.
Utilized by https://github.com/viamrobotics/rdk/pull/4848.

RSDK-10186 Allow specifying STDOUT/ERR loggers in process config

---

rpc/server.go

Adding additional shutdown log -- helped me find the spot for [this issue](https://viam.atlassian.net/browse/RSDK-10471)

Add debug logs for mdns server shutdown

---

rpc/wrtc_signaling_answerer.go
rpc/wrtc_signaling_test.go

- factor out deadline logic to `getDeadline`, add test
- more detailed logging
Necessary to establish a connection on a machine with an unsynchronized clock
We talked about using default offer deadline -- realized afterwards that because of network latency, we'd seldom be within this threshold. Sticking with 5 seconds for now. I think this logic needs redesign, but for now publishing as-is to patch.

adjust deadline forward when system clock is off

---

logger.go
rpc/wrtc_signaling_answerer.go

log grpc completion at debug level and `error connecting to peer` at warn
also preemptively downgraded other logs in rpc/wrtc_signaling_answerer.go

RSDK-10611 - Downgrade error log levels

---

rpc/wrtc_signaling.go

we were creating the slice at full length and then appending to it, but we should've allocated enough space for all elements but then only created the slice with length of the original list of ICE servers

RSDK-10615 - extendWebRTCConfig should not return extra empty ICE servers

---

pexec/managed_process.go

The previous PR for this ticket (#432) changed the behavior of `managedProcess.Stop` so that all calls to `Stop` would block on the management channel closing instead of just the fist one. Unfortunately this causes a deadlock if `Stop` is called before `Start`. We have a test for this but for some reason it did not cause the CI runs on the PR to fail and instead only failed when the PR was merged. I'll dig into that later but for now this hotfix adds a check to make sure the process was started before blocking on the management channel in `Stop`.

RSDK-10618: fixing deadlock in managedProcess when Stop is called before Start

---

rpc/wrtc_base_channel.go
rpc/wrtc_server.go
rpc/wrtc_signaling_answerer.go

RSDK-10183: Track PeerConnection disconnects in addition to active clients in FTDC.

---

go.mod
go.sum
rpc/wrtc_peer.go

~last one I promise~
I forgot RDK

RSDK-10711: Allow for true TCP relay candidates when `transport=tcp` exists in a turn ICEServer config string.

---

perf/exporters.go

https://viam.atlassian.net/browse/APP-8965
Cloud Run Services automatically get some env variables injected: https://cloud.google.com/run/docs/container-contract#env-vars. We have been relying on those being present to bootstrap our telemetry exporter. Those env variables are NOT injected for Cloud Run Worker Pool, no similar env variable is injected. Adding an option to set our own as a flallback.

Allow for fallback env variables to handle missing K_<X> env var from Cloud Run

---

rpc/dialer.go
rpc/wrtc_client_channel.go

pretty annoying. main blocker here is that the connection made using golang's grpc Dial is wrapped in a myriad of different structs depending on how it was called, which in our case ends up in a `clientConnRPCAuthenticator` which does not expose `grpc.ClientConn`. Doing a type check for `GrpcOverHTTPClientConn` suffices for now, however.
I imagine at some point we may want to fully move off of using dial in goutils for app connections, but tough to do that right now when there are so many utilities that we do rely on inside that function
this should be merged after rdk v0.94.0 is out

RSDK-11955 - Revert interface change

---

rpc/wrtc_call_queue_mongodb.go

We want expected connection failures to be a subset of all connection attempts so I re-ordered when each metric gets ordered so that this is the case

Reorder attempt and fail metrics
